package Preguntas;
import Modelo.Clases.Categoria;
import Modelo.Clases.Concurso;
import Modelo.Clases.Opcion;
import Modelo.Clases.Pregunta;

import java.util.*;

public  final class Preguntas {
    public static Categoria anadirPreguntasACategoriaDeMatematicas(){
        Opcion opcionUno = new Opcion ("2");
        Opcion opcionDos = new Opcion ("10");
        Opcion opcionTres = new Opcion("3");
        Opcion opcionCuatro=new Opcion("8");
        Opcion opcionCinco = new Opcion("4");
        LinkedHashMap<String, Opcion> opciones = new LinkedHashMap<>();
        opciones.put("a",opcionUno);
        opciones.put("b",opcionDos);
        opciones.put("c",opcionTres);
        opciones.put("d",opcionCuatro);
        opciones.put("e",opcionCinco);
        Pregunta pregunta = new Pregunta(opciones,"(1+1)*1",opcionUno);
        Opcion opcionUno1 = new Opcion("25");
        Opcion opcionDos2 = new Opcion("100");
        Opcion opcionTres3 = new Opcion("58");
        Opcion opcionCuatro4 = new Opcion("55");
        Opcion opcionCinco5 = new Opcion("60");
        LinkedHashMap<String, Opcion> opciones1 = new LinkedHashMap<>();
        opciones1.put("a",opcionUno1);
        opciones1.put("b",opcionDos2);
        opciones1.put("c",opcionTres3);
        opciones1.put("d",opcionCuatro4);
        opciones1.put("e",opcionCinco5);
        Pregunta pregunta1 = new Pregunta(opciones1,"Aproxima el número 58 a la decena",opcionCinco5);
        Opcion opcionUno2 = new Opcion("900");
        Opcion opcionDos3 = new Opcion("990");
        Opcion opcionTres4 = new Opcion("999");
        Opcion opcionCuatro5 = new Opcion("1000");
        Opcion opcionCinco6 = new Opcion("90");
        LinkedHashMap<String, Opcion> opciones2 = new LinkedHashMap<>();
        opciones2.put("a",opcionUno2);
        opciones2.put("b",opcionDos3);
        opciones2.put("c",opcionTres4);
        opciones2.put("d",opcionCuatro5);
        opciones2.put("e",opcionCinco6);
        Pregunta pregunta2 = new Pregunta(opciones2,"¿Cuál es el número anterior a 1000?",opcionTres4);
        Opcion opcionUno3 = new Opcion("10 kilos");
        Opcion opcionDos4 = new Opcion("15 kilos");
        Opcion opcionTres5 = new Opcion("30 kilos");
        Opcion opcionCuatro6 = new Opcion("20 kilos");
        Opcion opcionCinco7 = new Opcion("11 kilos");
        LinkedHashMap<String, Opcion> opciones3 = new LinkedHashMap<>();
        opciones3.put("a",opcionUno3);
        opciones3.put("b",opcionDos4);
        opciones3.put("c",opcionTres5);
        opciones3.put("d",opcionCuatro6);
        opciones3.put("e",opcionCinco7);
        Pregunta pregunta3 = new Pregunta(opciones3,"Un perro pesa 20 kilos y un cachorro pesa 10 kilos menos que él, ¿cuánto pesa la cría?",opcionUno3);
        Opcion opcionUno4 = new Opcion("15");
        Opcion opcionDos5 = new Opcion("10");
        Opcion opcionTres6 = new Opcion("30");
        Opcion opcionCuatro7 = new Opcion("20");
        Opcion opcionCinco8 = new Opcion("11");
        LinkedHashMap<String, Opcion> opciones4 = new LinkedHashMap<>();
        opciones4.put("a",opcionUno4);
        opciones4.put("b",opcionDos5);
        opciones4.put("c",opcionTres6);
        opciones4.put("d",opcionCuatro7);
        opciones4.put("e",opcionCinco8);
        Pregunta pregunta4 = new Pregunta(opciones4,"50/5",opcionDos5);
        List<Pregunta> preguntas = new ArrayList<Pregunta>();
        preguntas.add(pregunta);
        preguntas.add(pregunta1);
        preguntas.add(pregunta2);
        preguntas.add(pregunta3);
        preguntas.add(pregunta4);
        return new Categoria("Matemáticas básicas",preguntas,1);
    }
    public static Categoria anadirPreguntasACategoriaDeGeografia(){
        Opcion opcionUno = new Opcion("Paris");
        Opcion opcionDos = new Opcion("Alejandria");
        Opcion opcionTres = new Opcion("Amazonas");
        Opcion opcionCuatro = new Opcion("Bogotá");
        Opcion opcionCinco = new Opcion("Medellín");
        LinkedHashMap<String, Opcion> opciones = new LinkedHashMap<>();
        opciones.put("a",opcionUno);
        opciones.put("b",opcionDos);
        opciones.put("c",opcionTres);
        opciones.put("d",opcionCuatro);
        opciones.put("e",opcionCinco);
        Pregunta pregunta = new Pregunta(opciones,"¿Cuál es la capital de Colombia?",opcionCuatro);
        Opcion opcionUno1 = new Opcion("Paris");
        Opcion opcionDos2 = new Opcion("Italia");
        Opcion opcionTres3 = new Opcion("Lasagna");
        Opcion opcionCuatro4 = new Opcion("Vichi");
        Opcion opcionCinco5 = new Opcion("Munich");
        LinkedHashMap<String, Opcion> opciones1 = new LinkedHashMap<>();
        opciones1.put("a",opcionUno1);
        opciones1.put("b",opcionDos2);
        opciones1.put("c",opcionTres3);
        opciones1.put("d",opcionCuatro4);
        opciones1.put("e",opcionCinco5);
        Pregunta pregunta1 = new Pregunta(opciones1,"¿Cuál es la capital de Francia?",opcionUno1);
        Opcion opcionUno2 = new Opcion("San Andrés");
        Opcion opcionDos3 = new Opcion("Bucaramanga");
        Opcion opcionTres4 = new Opcion("Bolivar");
        Opcion opcionCuatro5 = new Opcion("Leticia");
        Opcion opcionCinco6 = new Opcion("Cartagena");
        LinkedHashMap<String, Opcion> opciones2 = new LinkedHashMap<>();
        opciones2.put("a",opcionUno2);
        opciones2.put("b",opcionDos3);
        opciones2.put("c",opcionTres4);
        opciones2.put("d",opcionCuatro5);
        opciones2.put("e",opcionCinco6);
        Pregunta pregunta2 = new Pregunta(opciones2,"¿Cuál ciudad colombiana es conocida como 'la ciudad amurallada'?",opcionCinco6);
        Opcion opcionUno3 = new Opcion("Canadá");
        Opcion opcionDos4 = new Opcion("EEUU kilos");
        Opcion opcionTres5 = new Opcion("Perú");
        Opcion opcionCuatro6 = new Opcion("Colombia");
        Opcion opcionCinco7 = new Opcion("Ecuador");
        LinkedHashMap<String, Opcion> opciones3 = new LinkedHashMap<>();
        opciones3.put("a",opcionUno3);
        opciones3.put("b",opcionDos4);
        opciones3.put("c",opcionTres5);
        opciones3.put("d",opcionCuatro6);
        opciones3.put("e",opcionCinco7);
        Pregunta pregunta3 = new Pregunta(opciones3,"¿En qué país puedes visitar Machu Picchu?",opcionTres5);
        Opcion opcionUno4 = new Opcion("China");
        Opcion opcionDos5 = new Opcion("India");
        Opcion opcionTres6 = new Opcion("El Vataticano");
        Opcion opcionCuatro7 = new Opcion("Rusia");
        Opcion opcionCinco8 = new Opcion("Mongolia");
        LinkedHashMap<String, Opcion> opciones4 = new LinkedHashMap<>();
        opciones4.put("a",opcionUno4);
        opciones4.put("b",opcionDos5);
        opciones4.put("c",opcionTres6);
        opciones4.put("d",opcionCuatro7);
        opciones4.put("e",opcionCinco8);
        Pregunta pregunta4 = new Pregunta(opciones4,"¿Cuál es el país más extenso de la tierra?",opcionCuatro7);
        List<Pregunta> preguntas = new ArrayList<Pregunta>();
        preguntas.add(pregunta);
        preguntas.add(pregunta1);
        preguntas.add(pregunta2);
        preguntas.add(pregunta3);
        preguntas.add(pregunta4);
        return new Categoria("Geografía básica",preguntas,2);
    }
    public static Categoria anadirPreguntasACategoriaDeHistoria(){
        Opcion opcionUno = new Opcion("Española");
        Opcion opcionDos = new Opcion("Haitiana");
        Opcion opcionTres = new Opcion("Francesa");
        Opcion opcionCuatro = new Opcion("Rusa");
        Opcion opcionCinco = new Opcion("Inglesa");
        LinkedHashMap<String, Opcion> opciones = new LinkedHashMap<>();
        opciones.put("a",opcionUno);
        opciones.put("b",opcionDos);
        opciones.put("c",opcionTres);
        opciones.put("d",opcionCuatro);
        opciones.put("e",opcionCinco);
        Pregunta pregunta = new Pregunta(opciones,"¿De qué nacionalidad era Juana de Arco?",opcionTres);
        Opcion opcionUno1 = new Opcion("Las islas Malvinas");
        Opcion opcionDos2 = new Opcion("Islas Marianas");
        Opcion opcionTres3 = new Opcion("Barú");
        Opcion opcionCuatro4 = new Opcion("San Andrés y providencia");
        Opcion opcionCinco5 = new Opcion("Liliput");
        LinkedHashMap<String, Opcion> opciones1 = new LinkedHashMap<>();
        opciones1.put("a",opcionUno1);
        opciones1.put("b",opcionDos2);
        opciones1.put("c",opcionTres3);
        opciones1.put("d",opcionCuatro4);
        opciones1.put("e",opcionCinco5);
        Pregunta pregunta1 = new Pregunta(opciones1,"¿Qué isla generó un conflicto entre Reino Unido y Argentina?",opcionUno1);
        Opcion opcionUno2 = new Opcion("Boliviano");
        Opcion opcionDos3 = new Opcion("Mexicano");
        Opcion opcionTres4 = new Opcion("Cubano");
        Opcion opcionCuatro5 = new Opcion("Argentino");
        Opcion opcionCinco6 = new Opcion("Ruso");
        LinkedHashMap<String, Opcion> opciones2 = new LinkedHashMap<>();
        opciones2.put("a",opcionUno2);
        opciones2.put("b",opcionDos3);
        opciones2.put("c",opcionTres4);
        opciones2.put("d",opcionCuatro5);
        opciones2.put("e",opcionCinco6);
        Pregunta pregunta2 = new Pregunta(opciones2,"¿De qué nacionalidad era Ernesto Ché Guevara?",opcionCuatro5);
        Opcion opcionUno3 = new Opcion("Colombia");
        Opcion opcionDos4 = new Opcion("Rusia");
        Opcion opcionTres5 = new Opcion("Alemania");
        Opcion opcionCuatro6 = new Opcion("Francia");
        Opcion opcionCinco7 = new Opcion("Austria");
        LinkedHashMap<String, Opcion> opciones3 = new LinkedHashMap<>();
        opciones3.put("a",opcionUno3);
        opciones3.put("b",opcionDos4);
        opciones3.put("c",opcionTres5);
        opciones3.put("d",opcionCuatro6);
        opciones3.put("e",opcionCinco7);
        Pregunta pregunta3 = new Pregunta(opciones3,"¿En que país nació Adolf Hitler?",opcionCinco7);
        Opcion opcionUno4 = new Opcion("Osama Bin Laden");
        Opcion opcionDos5 = new Opcion("Toro Sentado");
        Opcion opcionTres6 = new Opcion("John Adams");
        Opcion opcionCuatro7 = new Opcion("bernie sanders");
        Opcion opcionCinco8 = new Opcion("Oliver Stone");
        LinkedHashMap<String, Opcion> opciones4 = new LinkedHashMap<>();
        opciones4.put("a",opcionUno4);
        opciones4.put("b",opcionDos5);
        opciones4.put("c",opcionTres6);
        opciones4.put("d",opcionCuatro7);
        opciones4.put("e",opcionCinco8);
        Pregunta pregunta4 = new Pregunta(opciones4,"¿Quién fue el primer presidente de Estados Unidos?",opcionDos5);
        List<Pregunta> preguntas = new ArrayList<Pregunta>();
        preguntas.add(pregunta);
        preguntas.add(pregunta1);
        preguntas.add(pregunta2);
        preguntas.add(pregunta3);
        preguntas.add(pregunta4);
        Categoria categoria3 = new Categoria("Historia básica",preguntas,3);
        return categoria3;
    }
    public static Categoria anadirPreguntasACategoriaDeInformatica(){
        Opcion opcionUno = new Opcion("Windows, Mac Os, Linux");
        Opcion opcionDos = new Opcion("Office, Word, Excel");
        Opcion opcionTres = new Opcion("Mother Board, Mouse, Teclado");
        Opcion opcionCuatro = new Opcion("Internet, Servidor, Conexión FTP");
        Opcion opcionCinco = new Opcion("Java, Python, JavaScript");
        LinkedHashMap<String, Opcion> opciones = new LinkedHashMap<>();
        opciones.put("a",opcionUno);
        opciones.put("b",opcionDos);
        opciones.put("c",opcionTres);
        opciones.put("d",opcionCuatro);
        opciones.put("e",opcionCinco);
        Pregunta pregunta = new Pregunta(opciones,"¿Cual de las siguientes opciones corresponden a tipos de Sistemas Operativos Existentes en el mercado?",opcionUno);
        Opcion opcionUno1 = new Opcion("NetBeans, Eclipse");
        Opcion opcionDos2 = new Opcion("Windows, MacOs");
        Opcion opcionTres3 = new Opcion("Java, Python, JavaScript");
        Opcion opcionCuatro4 = new Opcion("Word, Excel, Power point");
        Opcion opcionCinco5 = new Opcion("Mouse, Teclado");
        LinkedHashMap<String, Opcion> opciones1 = new LinkedHashMap<>();
        opciones1.put("a",opcionUno1);
        opciones1.put("b",opcionDos2);
        opciones1.put("c",opcionTres3);
        opciones1.put("d",opcionCuatro4);
        opciones1.put("e",opcionCinco5);
        Pregunta pregunta1 = new Pregunta(opciones1,"¿Cual de las siguientes opciones corresponden a tipos de lenguajes de programación?",opcionTres3);
        Opcion opcionUno2 = new Opcion("Java, Python, JavaScript");
        Opcion opcionDos3 = new Opcion("Mouse, Teclado");
        Opcion opcionTres4 = new Opcion("NetBeans, Eclipse");
        Opcion opcionCuatro5 = new Opcion("Windows, MacOs");
        Opcion opcionCinco6 = new Opcion("Word, Excel, Power point");
        LinkedHashMap<String, Opcion> opciones2 =new LinkedHashMap<>();
        opciones2.put("a",opcionUno2);
        opciones2.put("b",opcionDos3);
        opciones2.put("c",opcionTres4);
        opciones2.put("d",opcionCuatro5);
        opciones2.put("e",opcionCinco6);
        Pregunta pregunta2 = new Pregunta(opciones2,"¿Cuales son ejemplos de herramientas ofimáticas?",opcionCinco6);
        Opcion opcionUno3 = new Opcion("El software almacenado en el hardware.");
        Opcion opcionDos4 = new Opcion("La unidad elemental de información.");
        Opcion opcionTres5 = new Opcion("La forma de almacenar datos.");
        Opcion opcionCuatro6 = new Opcion(" La forma de manipular y recuperar datos.");
        Opcion opcionCinco7 = new Opcion("Un conjunto de programas que se encargan de controlar la computadora");
        LinkedHashMap<String, Opcion> opciones3 = new LinkedHashMap<>();
        opciones3.put("a",opcionUno3);
        opciones3.put("b",opcionDos4);
        opciones3.put("c",opcionTres5);
        opciones3.put("d",opcionCuatro6);
        opciones3.put("e",opcionCinco7);
        Pregunta pregunta3 = new Pregunta(opciones3,"El sistema operativo es:",opcionCinco7);
        Opcion opcionUno4 = new Opcion("Software");
        Opcion opcionDos5 = new Opcion("Hardware");
        Opcion opcionTres6 = new Opcion("Teclado");
        Opcion opcionCuatro7 = new Opcion("Java");
        Opcion opcionCinco8 = new Opcion("Windows");
        LinkedHashMap<String, Opcion> opciones4 = new LinkedHashMap<>();
        opciones4.put("a",opcionUno4);
        opciones4.put("b",opcionDos5);
        opciones4.put("c",opcionTres6);
        opciones4.put("d",opcionCuatro7);
        opciones4.put("e",opcionCinco8);
        Pregunta pregunta4 = new Pregunta(opciones4,"La parte física de la computadora es conocida como: ",opcionDos5);
        List<Pregunta> preguntas = new ArrayList<Pregunta>();
        preguntas.add(pregunta);
        preguntas.add(pregunta1);
        preguntas.add(pregunta2);
        preguntas.add(pregunta3);
        preguntas.add(pregunta4);
        Categoria categoria4 = new Categoria("Informática básica",preguntas,4);
        return categoria4;
    }
    public static Categoria anadirPreguntasACategoriaDeProgramacion(){
        Opcion opcionUno = new Opcion("Es el seguimiento del diagrama de flujo de datos para la solución a un problema.");
        Opcion opcionDos = new Opcion("Es una serie de pasos para dar solución a un problema.");
        Opcion opcionTres = new Opcion("Es el orden de los pasos para un sistema de informacion.");
        Opcion opcionCuatro = new Opcion("Es el estudio de las ordenes creadas por un programador.");
        Opcion opcionCinco = new Opcion("Es un entorno de desarrollo");
        LinkedHashMap<String, Opcion> opciones = new LinkedHashMap<>();
        opciones.put("a",opcionUno);
        opciones.put("b",opcionDos);
        opciones.put("c",opcionTres);
        opciones.put("d",opcionCuatro);
        opciones.put("e",opcionCinco);
        Pregunta pregunta = new Pregunta(opciones,"¿Que es un algoritmo?",opcionDos);
        Opcion opcionUno1 = new Opcion("SELECT FROM EMPRESA");
        Opcion opcionDos2 = new Opcion("SELECT ALL FROM EMPRESA");
        Opcion opcionTres3 = new Opcion("SELECT EMPRESA");
        Opcion opcionCuatro4 = new Opcion("SELECT * FROM EMPRESA");
        Opcion opcionCinco5 = new Opcion("RETURN ALL EMPRESA");
        LinkedHashMap<String, Opcion> opciones1 = new LinkedHashMap<>();
        opciones1.put("a",opcionUno1);
        opciones1.put("b",opcionDos2);
        opciones1.put("c",opcionTres3);
        opciones1.put("d",opcionCuatro4);
        opciones1.put("e",opcionCinco5);
        Pregunta pregunta1 = new Pregunta(opciones1,"Una consulta para ejecutar todos los datos de una tabla llamada EMPRESA, tiene la siguiente estructura:",opcionCinco5);
        Opcion opcionUno2 = new Opcion("JAVA");
        Opcion opcionDos3 = new Opcion("MYSQL");
        Opcion opcionTres4 = new Opcion("PYTHON");
        Opcion opcionCuatro5 = new Opcion("EXCEL");
        Opcion opcionCinco6 = new Opcion("WORD");
        LinkedHashMap<String, Opcion> opciones2 = new LinkedHashMap<>();
        opciones2.put("a",opcionUno2);
        opciones2.put("b",opcionDos3);
        opciones2.put("c",opcionTres4);
        opciones2.put("d",opcionCuatro5);
        opciones2.put("e",opcionCinco6);
        Pregunta pregunta2 = new Pregunta(opciones2,"Uno de los motores de bases de datos más conocidos es... ",opcionDos3);
        Opcion opcionUno3 = new Opcion("CSS");
        Opcion opcionDos4 = new Opcion("HTML");
        Opcion opcionTres5 = new Opcion("React");
        Opcion opcionCuatro6 = new Opcion("Angular");
        Opcion opcionCinco7 = new Opcion("JAVA");
        LinkedHashMap<String, Opcion> opciones3 = new LinkedHashMap<>();
        opciones3.put("a",opcionUno3);
        opciones3.put("b",opcionDos4);
        opciones3.put("c",opcionTres5);
        opciones3.put("d",opcionCuatro6);
        opciones3.put("e",opcionCinco7);
        Pregunta pregunta3 = new Pregunta(opciones3,"¿Qué lenguajes usamos más del lado del servidor?",opcionCinco7);
        Opcion opcionUno4 = new Opcion("Una plantilla para crear objetos");
        Opcion opcionDos5 = new Opcion("Son varios objetos heredados");
        Opcion opcionTres6 = new Opcion("Un lenguajes de programación");
        Opcion opcionCuatro7 = new Opcion("Todas las anteriores");
        Opcion opcionCinco8 = new Opcion("Ninguna opción es correcta");
        LinkedHashMap<String, Opcion> opciones4 = new LinkedHashMap<>();
        opciones4.put("a",opcionUno4);
        opciones4.put("b",opcionDos5);
        opciones4.put("c",opcionTres6);
        opciones4.put("d",opcionCuatro7);
        opciones4.put("e",opcionCinco8);
        Pregunta pregunta4 = new Pregunta(opciones4,"Una clase puede ser: ",opcionDos5);
        List<Pregunta> preguntas = new ArrayList<Pregunta>();
        preguntas.add(pregunta);
        preguntas.add(pregunta1);
        preguntas.add(pregunta2);
        preguntas.add(pregunta3);
        preguntas.add(pregunta4);
        Categoria categoria5 = new Categoria("Programación básica",preguntas,5);
        return categoria5;
    }

    public static List<Categoria> unirCategorias() {
        List<Categoria> categorias = new ArrayList<>();
        categorias.add(anadirPreguntasACategoriaDeMatematicas());
        categorias.add(anadirPreguntasACategoriaDeGeografia());
        categorias.add(anadirPreguntasACategoriaDeHistoria());
        categorias.add(anadirPreguntasACategoriaDeInformatica());
        categorias.add(anadirPreguntasACategoriaDeProgramacion());
        return categorias;
    }

    public static Concurso createContest(String contestName){
        return new Concurso(unirCategorias(),contestName);
    }

    }

